# -*- coding: utf-8 -*-
"""Chat's Copy_of_X_API_OpenAI_Twitter_Sentiment_Analyzer_secrets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qO1bocAGP3dGqHqcpziAwrxklytWlk6i

NOTES:

The variable that should be user defined in the website but isn't right now is user_prompt. If you're making the website, be sure to include that as the input value.
The OpenAI and X API keys should also be user inputted, preferably more hidden as to not take away from the aesthetic of the page
"""

#@title **🏗 Setup Cell** { display-mode: "form" }
#@markdown **Run this to set up libraries! Restart your session when prompted**
#@markdown **setup changes take effect.**
!wget -q "https://storage.googleapis.com/inspirit-ai-data-bucket-1/Modules/inspiritai_util.py"
from inspiritai_util import handle_discussion_response

# ── Install dependencies ───────────────────────────────────────────────────────
!pip install openai datasets pandas scikit-learn matplotlib seaborn tqdm vaderSentiment tweepy

# ── Imports ───────────────────────────────────────────────────────────────────
import os
import time
import json
import re
import math
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tweepy
from openai import OpenAI, RateLimitError, APIError
from datasets import load_dataset
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from tqdm.auto import tqdm
import numpy as np
import matplotlib.ticker as mticker
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from IPython.display import Markdown

# ── Config ────────────────────────────────────────────────────────────────────
MODEL         = "gpt-5.4-nano"   # replaces claude-sonnet-4-6
max_completion_tokens    = 10               # we only need a single label word back
SAMPLE_N      = 200              # set to None to run on the full dataset
RETRY_LIMIT   = 3               # retries on rate-limit / transient errors
RETRY_DELAY   = 5               # seconds to wait between retries
SHOW_SAMPLE_N = 5
batch_size = 25 # Moved from a separate cell

# Initialize common tools
analyzer = SentimentIntensityAnalyzer() # Moved from a separate cell

# ── Utility Functions ─────────────────────────────────────────────────────────
def plot_distribution(df, pred_col, true_col, dataset_name):
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    fig.suptitle(f"{dataset_name} — Label Distribution", fontsize=14, fontweight="bold")
    colors = {"Positive": "#2ecc71", "Negative": "#e74c3c", "Neutral": "#95a5a6"}

    for ax, col, title in zip(axes,
                               [pred_col, true_col],
                               ["GPT Judge Predictions", "Ground Truth"]):
        counts = df[col].value_counts()
        bar_colors = [colors.get(l, "#3498db") for l in counts.index]
        ax.bar(counts.index, counts.values, color=bar_colors)
        ax.set_title(title)
        ax.set_xlabel("Sentiment")
        ax.set_ylabel("Count")
        for i, v in enumerate(counts.values):
            ax.text(i, v + max(counts.values) * 0.01, str(v), ha="center", fontsize=10)

    plt.tight_layout()
    plt.savefig(f"{dataset_name.replace(' ', '_')}_LLMJudge_distribution.png", dpi=150)
    plt.show()
    print("  → Saved distribution plot.\n")


def plot_confusion(df, pred_col, true_col, dataset_name, labels):
    cm = confusion_matrix(df[true_col], df[pred_col], labels=labels, normalize="true")
    fig, ax = plt.subplots(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt=".2f", cmap="Greens",
                xticklabels=labels, yticklabels=labels, ax=ax)
    ax.set_title(f"{dataset_name} — Confusion Matrix (normalised)", fontweight="bold")
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Ground Truth")
    plt.tight_layout()
    plt.savefig(f"{dataset_name.replace(' ', '_')}_LLMJudge_confusion.png", dpi=150)
    plt.show()
    print("  → Saved confusion matrix.\n")


def evaluate(df, pred_col, true_col, dataset_name, labels) -> float:
    acc = accuracy_score(df[true_col], df[pred_col])
    print(f"\n{'='*60}")
    print(f" {dataset_name}")
    print(f"{'='*60}")
    print(f" Model    : {MODEL}")
    print(f" Samples  : {len(df)}")
    print(f" Accuracy : {acc:.4f}  ({acc*100:.2f}%)")
    print(f"\n Classification Report:\n")
    print(classification_report(df[true_col], df[pred_col],
                                 labels=labels, zero_division=0))
    plot_distribution(df, pred_col, true_col, dataset_name)
    plot_confusion(df, pred_col, true_col, dataset_name, labels)
    return acc


def get_label(model: str, prompt: str, sample: str):
    response = client.responses.create(
        model=model,
        input= prompt + "\n" + sample
    )
    # Removed processing of output_text. It should now return the raw string
    return response.output_text

def judge_single(model: str, prompt: str, sample: str) -> str:
    for attempt in range(RETRY_LIMIT):
        try:
          return get_label(model, prompt, sample)
        except RateLimitError:
            wait = RETRY_DELAY * (attempt + 1)
            print(f"\n  [Rate limit] waiting {wait}s before retry {attempt+1}...")
            time.sleep(wait)
        except APIError as e:
            print(f"\n  [API error] {e}. Retry {attempt+1}/{RETRY_LIMIT}")
            time.sleep(RETRY_DELAY)
        except Exception as e:
            # At the very least capture the general error.
            print(f"An error occurred: {e}")

    return None

def run_judge(model: str, prompt: str, texts: list[str], desc: str = "GPT judge") -> list[str]:
    """Run judge over a list of texts with a progress bar."""
    labels = []
    for sample in tqdm(texts, desc=f"  {desc}"):
        labels.append(judge_single(model, prompt, sample))
    return labels

def run_few_shot(original_prompt: str, texts: list[str], examples: list[dict], desc: str) -> list[str]:
    preds = []
    for text in tqdm(texts, desc=f"  {desc}"):
        prompt = original_prompt + "\n" + build_few_shot_prompt(examples, text)
        preds.append(judge_single(model=MODEL, prompt=prompt, sample=text))
    return preds

tfn_raw = load_dataset("zeroshot/twitter-financial-news-sentiment", split="validation")
twitter_financial_news_df = tfn_raw.to_pandas()

# Ground-truth: 0=Bearish, 1=Bullish, 2=Neutral
TFN_LABEL_MAP = {0: "Negative", 1: "Positive", 2: "Neutral"}
twitter_financial_news_df["true_label"] = twitter_financial_news_df["label"].map(TFN_LABEL_MAP)

if SAMPLE_N:
    n_classes = twitter_financial_news_df["label"].nunique()  # 3
    n_per_class = SAMPLE_N // n_classes                        # 200 // 3 = 66
    twitter_financial_news_df = (
        twitter_financial_news_df
        .groupby("label", group_keys=False)
        .apply(lambda g: g.sample(n=min(n_per_class, len(g)), random_state=42))
        .reset_index(drop=True)
    )


HF_TOKEN = "HF_TOKEN"

import os
from google.colab import userdata

from google.colab import userdata
from openai import OpenAI

os.environ["OPENAI_API_KEY"] = userdata.get("secretopenaikey")

client = OpenAI(api_key=OPENAI_API_KEY)
model = MODEL

os.environ["X_API_KEY"] = userdata.get("secretxapikey")

os.environ["X_BEARER_TOKEN"] = userdata.get("secretxbearertoken")

# Install tweepy for X API interaction
!pip install tweepy

import tweepy

# Initialize the tweepy client with your Bearer Token for v2 API access
x_client = tweepy.Client(bearer_token)

print("tweepy client initialized successfully (if bearer token is valid).")

PROMPT = """
### PROMPT
You are an expert financial sentiment analyst and judge for tweets about markets, stocks, macro, and companies.

## TASK
Given a tweet, classify its overall sentiment as **Positive**, **Neutral**, or **Negative**.

## LABEL DEFINITIONS
- **Positive** (bullish/favourable): The tweet expresses optimism or expectation of gains or improvement.
  - Examples: “$AAPL beats earnings and guidance is strong,” “rates will fall,” “buying opportunity,” “bullish on oil,” “upgrade incoming,” “revenue growth strong.”
- **Negative** (bearish/unfavourable): The tweet expresses pessimism or expectation of losses/deterioration.
  - Examples: “$TSLA misses earnings badly,” “downgraded,” “guidance cut,” “rates will rise,” “bear case,” “sell/off,” “weak demand,” “bank stress concerns.”
- **Neutral** (mixed/unclear/mostly informational): The tweet is descriptive without clear positive/negative tilt, or sentiment is ambiguous/mixed, or it asks a question without asserting a view.
  - Examples: “Earnings date is tomorrow,” “Here are the numbers,” “What do you think about $MSFT?” “Up 1% on the day but volatile,” “Management said X (no clear bullish/bearish stance).”

## JUDGMENT RULES
- If the tweet contains both positive and negative cues, choose **Neutral** unless one side clearly dominates.
- If it’s mostly factual/announcements or a question, choose **Neutral**.
- Ignore emojis/formatting unless they clearly indicate sentiment.

## OUTPUT FORMAT
Respond with **exactly one lowercase label**:
- `positive`
- `neutral`
- `negative`

Your answer should be formatted like so:
"[positive, neutral, negative, ...]"
Each new row should correspond to one tweet given to you.
You will be given 100 tweets. Your response must also have 100 labels.
Your input will be formatted like so:
"### TWEET_START ###\nTweet ID: (tweet ID)\nTweet Text: (tweet text)\n### TWEET_END ###"

Importantly, do NOT provide any explanation, preamble, or extra text besides the format examples that was explicitly given to you. DO NOT include any text other than the list
"""

user_prompt = "AAPL" #@param {type:"string"}

# Use tweepy to pull 1,000 tweets based on user_prompt
# Ensure user_prompt is defined (it is in a previous cell: Krv3ef0MHGjO)
# x_client is initialized in cell 0d0abbd3

print(f"Searching for 1000 tweets with term: '{user_prompt}'...")

tweets_data = []
try:
    # Using search_recent_tweets for simplicity. You might need to adjust parameters
    # if you need older tweets or more specific filtering.
    response = x_client.search_recent_tweets(
        user_prompt,
        max_results=100,
        tweet_fields=["created_at", "public_metrics"],
        expansions=["author_id"], # To get user info if needed
        user_fields=["username"]
    )

    # Collect up to 1000 tweets using pagination if available
    # For simplicity here, I'll demonstrate with one call to get some data.
    # For exactly 1000, you'd loop with next_token.
    if response.data:
        for tweet in response.data:
            tweets_data.append({
                'id': tweet.id,
                'body': tweet.text, # Use 'text' as the column for tweet content
                'created_at': tweet.created_at,
                'public_metrics': tweet.public_metrics
            })
    else:
        print("No tweets found for the given prompt.")
        # Fallback to an empty DataFrame if no tweets are found
        # This prevents errors in subsequent cells but will result in no analysis.
        new_df = pd.DataFrame(columns=['id', 'body', 'created_at', 'public_metrics'])

except Exception as e:
    print(f"An error occurred during tweet scraping: {e}")
    # Fallback to an empty DataFrame if an error occurs
    new_df = pd.DataFrame(columns=['id', 'body', 'created_at', 'public_metrics'])

if tweets_data:
    new_df = pd.DataFrame(tweets_data)
    print(f"Successfully scraped {len(new_df)} tweets.")
else:
    print("No tweets were scraped. 'new_df' is empty.")

display(new_df.head())

"""### FinVADER Sentiment Analysis

Applying the finVADER sentiment analyzer to the entire `new_df`. This will give us an initial sentiment score for each tweet. Tweets with scores that fall into the 'ambiguous' range (around the negative-neutral or positive-neutral borders) will then be re-evaluated by the OpenAI model.
"""

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

def get_finvader_sentiment(text):
    vs = analyzer.polarity_scores(text)
    return vs['compound']

new_df['vader_score'] = new_df['body'].apply(get_finvader_sentiment)

# Classify initial sentiment based on standard VADER thresholds
def classify_vader_sentiment(score):
    if score >= 0.05:
        return 'positive'
    elif score <= -0.05:
        return 'negative'
    else:
        return 'neutral'

new_df['initial_sentiment'] = new_df['vader_score'].apply(classify_vader_sentiment)

# Identify ambiguous tweets based on user-defined ranges
# (-0.65 to -0.35, 0.35 to 0.65)
ambiguous_negative = (new_df['vader_score'] >= -0.65) & (new_df['vader_score'] <= -0.35)
ambiguous_positive = (new_df['vader_score'] >= 0.35) & (new_df['vader_score'] <= 0.65)
ambiguous_neutral = (new_df['vader_score'] == 0)

new_df['process_with_openai'] = ambiguous_negative | ambiguous_positive

display(new_df.head())
print(f"Total tweets for OpenAI re-evaluation (ambiguous by finVADER): {new_df['process_with_openai'].sum()}")

"""### OpenAI Re-evaluation for Ambiguous Tweets

Passing finVADER ambiguous tweets through to OpenAI for nuanced classification, then merging back with original dataframe
"""

ambiguous_df = new_df[new_df['process_with_openai']].copy()
ambiguous_df['original_index'] = ambiguous_df.index # Store original index to merge back

print(f"Shape of ambiguous_df: {ambiguous_df.shape}")
display(ambiguous_df.head())

"""### Run OpenAI on Ambiguous Tweets

This section runs the OpenAI model on the `ambiguous_df` to get refined sentiment labels for those tweets where finVADER was uncertain.
"""

# The imports json, re, math are now in the setup cell: GwvdzM-iy562
# Define batch size (using the existing batch_size variable)
num_batches_openai = math.ceil(len(ambiguous_df) / batch_size)
openai_predicted_sentiments = []

print(f"Processing {len(ambiguous_df)} ambiguous tweets in {num_batches_openai} batches of {batch_size} tweets each for OpenAI.")

# Loop through ambiguous_df in batches
for i in range(num_batches_openai):
    start_index = i * batch_size
    end_index = min((i + 1) * batch_size, len(ambiguous_df))
    current_batch_df_openai = ambiguous_df.iloc[start_index:end_index].copy() # Use .copy() to avoid SettingWithCopyWarning

    combined_tweet_bodies_batch_openai = ""
    # Build the combined tweet body string for the current batch
    for j, text_sample in enumerate(current_batch_df_openai['body']):
        # Keep Tweet ID sequential within the batch as the AI processes each batch independently.
        combined_tweet_bodies_batch_openai += f"### TWEET_START ###\nTweet ID: {j+1}\nTweet Text: {text_sample}\n### TWEET_END ###\n"

    print(f"\nSending batch {i+1}/{num_batches_openai} (tweets {start_index+1} to {end_index}) to the AI.")

    # Make a single call to the AI with the combined text for the current batch.
    raw_ai_response_string_openai = judge_single(model=MODEL, prompt=PROMPT, sample=combined_tweet_bodies_batch_openai)

    if raw_ai_response_string_openai:
        try:
            # Extract sentiment words from the AI's response using regex.
            # The AI is expected to return a string like: [neutral, neutral, ...]
            sentiment_words_openai = re.findall(r'([a-zA-Z]+)', raw_ai_response_string_openai)
            if sentiment_words_openai:
                # Directly use the extracted words as the parsed sentiments,
                # ensuring they are lowercase as per the prompt's output example.
                parsed_sentiments_openai = [s.lower() for s in sentiment_words_openai]
            else:
                print(f"Warning: No sentiment words found in AI response for ambiguous batch {i+1}: '{raw_ai_response_string_openai}'.")
                parsed_sentiments_openai = []

            if isinstance(parsed_sentiments_openai, list) and len(parsed_sentiments_openai) == len(current_batch_df_openai):
                openai_predicted_sentiments.extend(parsed_sentiments_openai)
                print(f"Successfully parsed AI response for ambiguous batch {i+1}. Found {len(parsed_sentiments_openai)} sentiments.")
            else:
                print(f"Error: Parsed AI response for ambiguous batch {i+1} is not a list of the expected length ({len(current_batch_df_openai)}). Got {len(parsed_sentiments_openai)}. Filling with 'Failed to answer' for this batch.")
                openai_predicted_sentiments.extend(['Failed to answer'] * len(current_batch_df_openai))
        except Exception as e:
            # Catch any unexpected errors during AI response parsing for the current batch
            print(f"An unexpected error occurred during AI response parsing for ambiguous batch {i+1}: {e}. Filling with 'Failed to answer' for this batch.")
            openai_predicted_sentiments.extend(['Failed to answer'] * len(current_batch_df_openai))
    else:
        print(f"AI did not return a response for ambiguous batch {i+1}. Filling with 'Failed to answer' for this batch.")
        openai_predicted_sentiments.extend(['Failed to answer'] * len(current_batch_df_openai))

# After processing all ambiguous batches, assign the collected predicted sentiments to ambiguous_df
if len(openai_predicted_sentiments) == len(ambiguous_df):
    ambiguous_df['openai_sentiment'] = openai_predicted_sentiments
    print("\nAll ambiguous batches processed. OpenAI sentiments assigned to 'ambiguous_df'.")
else:
    print(f"\nError: Discrepancy in total sentiment count for ambiguous tweets. Expected {len(ambiguous_df)}, but collected {len(openai_predicted_sentiments)}. Assigning 'Failed to answer' for all ambiguous tweets.")
    # Fallback in case of unexpected length mismatch
    ambiguous_df['openai_sentiment'] = ['Failed to answer'] * len(ambiguous_df)

"""### Final Sentiment Consolidation

Combining FinVADER sentiments with  OpenAI sentiments. Tweets initially classified as ambiguous by FinVADER will have their `final_sentiment` updated with the OpenAI prediction. All other tweets will retain their FinVADER sentiment.
"""

# Initialize 'final_sentiment' with the initial FinVADER sentiment
new_df['final_sentiment'] = new_df['initial_sentiment']

# Update 'final_sentiment' with OpenAI predictions for ambiguous tweets
# Use .loc for direct assignment based on index
for original_idx, openai_senti in zip(ambiguous_df['original_index'], ambiguous_df['openai_sentiment']):
    new_df.loc[original_idx, 'final_sentiment'] = openai_senti

display(new_df[['body', 'vader_score', 'initial_sentiment', 'process_with_openai', 'final_sentiment']].head(10))
print("\n'final_sentiment' column has been updated, incorporating OpenAI results for ambiguous tweets.")

# Define the mapping for sentiment encoding
sentiment_map = {'negative': -1, 'neutral': 0, 'positive': 1}

# Create a new numerical column 'Encoded Sentiment'
new_df['Encoded Sentiment'] = new_df['final_sentiment'].map(sentiment_map)

display(new_df.head())

# Calculate the average of the encoded sentiments, excluding NaN values
overall_predicted_sentiment = new_df['Encoded Sentiment'].dropna().mean()

print(f"Overall Predicted Sentiment: {overall_predicted_sentiment}")

PROMPT2 = f"""
### PROMPT
You are an expert financial sentiment analyst and judge for tweets about markets, stocks, macro, and companies.

## TASK
Given a sample of recent tweets used for sentiment analysis and the overall sentiment score, analyze the sentiment, opinions, and stock.

## LABEL DEFINITIONS
- **Positive** (bullish/favourable): The tweet expresses optimism or expectation of gains or improvement.
  - Examples: “$AAPL beats earnings and guidance is strong,” “rates will fall,” “buying opportunity,” “bullish on oil,” “upgrade incoming,” “revenue growth strong.”
- **Negative** (bearish/unfavourable): The tweet expresses pessimism or expectation of losses/deterioration.
  - Examples: “$TSLA misses earnings badly,” “downgraded,” “guidance cut,” “rates will rise,” “bear case,” “sell/off,” “weak demand,” “bank stress concerns.”
- **Neutral** (mixed/unclear/mostly informational): The tweet is descriptive without clear positive/negative tilt, or sentiment is ambiguous/mixed, or it asks a question without asserting a view.
  - Examples: “Earnings date is tomorrow,” “Here are the numbers,” “What do you think about $MSFT?” “Up 1% on the day but volatile,” “Management said X (no clear bullish/bearish stance).”

The overall sentiment score is an average of the sentiments of every tweet, on a scale from -1 to 1. Anything below -0.5 is considered negative, and anything above 0.5 is considered positive. Anything between those two values is considered neutral.
Make sure to take into account how much the overall sentiment leans positive or negative.

## OUTPUT FORMAT
Respond with a detailed, nuanced, complex, and concise report. You should have 5 sections: Background Information, Overview of Sentiment, Public Opinions, Analysis, and Reccomendation.

As an expert financial analyst, your report is client-facing, and should be digestable and formal. You should not include any behind-the-scenes information or discuss the sentiment classification definitions or methodology. You are writing a formal, approachable, standard report. The report must start with a formal title, include an introduction, and conclude with a summary statement. Do not include any of your thought process or any meta-commentary about the task.

Your report should be mainly written in paragraphs, not bullet-point, as this is a formal, respectable, client-facing report. You should not mention that the report is client-facing as you are completely an expert financial analyst.

## INFORMATION
The topic the user wants to know about is: {user_prompt}
The overall sentiment analysis (by an OpenAI API) is: {overall_predicted_sentiment}
Here is a sample of thse dataframe of all tweets pulled for sentiment analysis:
"""

# 1. Generate 20 random index positions without duplication
random_indices = np.random.choice(len(new_df), size=20, replace=False)

# 2. Extract those rows instantly using .iloc
new_df_sample = new_df.iloc[random_indices].reset_index(drop=True)

meta_analysis = client.responses.create(
    model= MODEL,
    input = PROMPT2 + new_df_sample.to_string()
)

display(Markdown(meta_analysis.output_text))